spring:
  datasource:
    url: jdbc:postgresql://213.5.111.52:54321/SpringStudy
    username: postgres
    password: 15948Post
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true